language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  global:
    secure: omFMs9SEGjhu4q4oVpF08LaPhh8q9ytaerRVyo1TrAdWsxNGfqjgUFHEFUN56AecmP31atwcA0EdBc+qmbxH/fHQIlQAU38vlfn6b9VuAW8h2pjhimxYuz6eAob47nLyPxMDqKeJSpNhmj1CN+fxWL2SxZWIsWHqq4jGlkn+Ft0=

before_install:
  - sudo apt-get install -qq gfortran
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose pytest flake8 sphinx lxml sqlalchemy netcdf4 tornado future
  # Only install the theme for Python 2.7 as it builds the docs.
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install sphinx-bootstrap-theme ; fi
  # Currently only the ObsPy master supports Python 3.
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install "mock<1.0" obspy; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install mock obspy ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install mock https://github.com/obspy/obspy/archive/master.zip ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install mock https://github.com/obspy/obspy/archive/master.zip ; fi
  - pip install coveralls
  - pip install requests responses

install:
  - git version
  - git fetch origin --tags --unshallow
  - git remote add instaseis git://github.com/krischer/instaseis.git
  - git fetch instaseis --tags
  - git status
  - pip install --no-deps -v -e .
  - git status

script:
  - coverage run --source=instaseis -m instaseis.tests
  # Docs only need to be built once.
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then cd $TRAVIS_BUILD_DIR/doc; make html ; fi

after_success:
  - cd $TRAVIS_BUILD_DIR; coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then bash $TRAVIS_BUILD_DIR/.travis-update-gh-pages.sh ; fi
